name: test-action
on:
  push:
    branches:
      - master
jobs:
  test-generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: test action
        uses: navikt/pam-generate-release-action@v1.2
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          useLatestReleaseTag: true
          cmd: "--usernames-as-github-logins"
      - name: Output changelog
        run: cat CHANGELOG.md